name: 'Sinhala Quotes'
author: 'Dinush Chathurya'
description: 'Updates README with a Sinhala Quote'
inputs:
  category: 
    description: 'Quote category to fetch'
    required: false
    default: 'inspire' 
  readme_path:
    description: 'Path of the readme file to update'
    default: "./README.md"
    required: false
runs:
  using: 'node12'
  main: 'index.js'
