name: 'Quote Of The Day Action'
author: 'Dinush Chathurya'
description: 'Updates README with a quote of the day'
inputs:
  readme_path:
    description: 'Path of the readme file to update'
    default: "./README.md"
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'message-circle'
  color: 'white'
