name: 'Sinhala Quote Of The Day'
author: 'Dinush Chathurya'
description: 'Updates README with a Sinhala quote'
inputs:
  readme_path:
    description: 'Path of the readme file to update'
    default: "./README.md"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-circle'
  color: 'white'
