name: Update README with QOTD

on:
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *" # triggers every 5 minitues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install node dependencies
      run: npm install

    - name: Sinhala Quote Of The Day
      uses: ./


